# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")
    increment_build_number(xcodeproj: "MyMemory.xcodeproj")
    build_app(scheme: "MyMemory")
    api_key = app_store_connect_api_key(
      key_id: "Z977X9A9MU",
      issuer_id: "90703bce-fcb0-43fb-bfbd-5d3d352df494",
      key_filepath: "./AuthKey_Z977X9A9MU.p8",
      duration: 1200,
      in_house: false
    )
    pilot(api_key: api_key)
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
